[build]
  base = "vendorpasshelp-main"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "vendorpasshelp-main/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
